name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: testWeightConvert
      id: testweightconvert
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testWeightConvert
        setup-command: ''
        command: python test_main.py
        timeout: 5
        max-score: 100
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TESTWEIGHTCONVERT_RESULTS: "${{steps.testweightconvert.outputs.result}}"
      with:
        runners: testweightconvert
